copy H:\crass\cui\BaldrX\Release\BaldrX.dll cui\BaldrX.cui
copy H:\crass\cui\DaiSystem\Release\DaiSystem.dll cui\DaiSystem.cui
copy H:\crass\cui\CIRCUS\Release\CIRCUS.dll cui\CIRCUS.cui
copy H:\crass\cui\ExHIBIT\Release\ExHIBIT.dll cui\ExHIBIT.cui
copy H:\crass\cui\Hypatia\Release\Hypatia.dll cui\Hypatia.cui
copy H:\crass\cui\InnocentGrey\Release\InnocentGrey.dll cui\InnocentGrey.cui
copy H:\crass\cui\LiosGame\Release\LiosGame.dll cui\LiosGame.cui
copy H:\crass\cui\BLUEGALE\Release\BLUEGALE.dll cui\BLUEGALE.cui
copy H:\crass\cui\YaneuraoGame\Release\YaneuraoGame.dll cui\YaneuraoGame.cui
copy H:\crass\cui\MarbleEngine\Release\MarbleEngine.dll cui\MarbleEngine.cui
copy H:\crass\cui\FS\Release\FS.dll cui\FS.cui
copy H:\crass\cui\ktg\Release\ktg.dll cui\ktg.cui
copy H:\crass\cui\AIMS\Release\AIMS.dll cui\AIMS.cui
copy H:\crass\cui\Lucifen\Release\Lucifen.dll cui\Lucifen.cui
copy H:\crass\cui\IkuraGDL\Release\IkuraGDL.dll cui\IkuraGDL.cui
copy H:\crass\cui\YU-RIS\Release\YU_RIS.dll cui\YU-RIS.cui
copy H:\crass\cui\AF\Release\AF.dll cui\AF.cui
copy H:\crass\cui\NGS\Release\NGS.dll cui\NGS.cui
copy H:\crass\cui\AZSystem\Release\AZSystem.dll cui\AZSystem.cui
copy H:\crass\cui\LIBIDO\Release\LIBIDO.dll cui\LIBIDO.cui
copy H:\crass\cui\QLIE\Release\QLIE.dll cui\QLIE.cui
copy H:\crass\cui\GLib2\Release\GLib2.dll cui\GLib2.cui
copy H:\crass\cui\GLib\Release\GLib.dll cui\GLib.cui
copy H:\crass\cui\NSystem\Release\NSystem.dll cui\NSystem.cui
copy H:\crass\cui\yuLib\Release\yuLib.dll cui\yuLib.cui
copy H:\crass\cui\bruns_system\Release\bruns_system.dll cui\bruns-system.cui
copy H:\crass\cui\Illusion\Release\Illusion.dll cui\Illusion.cui
copy H:\crass\cui\TmrHiroADVSystem\Release\TmrHiroADVSystem.dll cui\TmrHiroADVSystem.cui
copy H:\crass\cui\C4\Release\C4.dll cui\C4.cui
copy H:\crass\cui\BladeEngine\Release\BladeEngine.dll cui\BladeEngine.cui
copy H:\crass\cui\BSXX\Release\BSXX.dll cui\BSXX.cui
copy H:\crass\cui\AFS\Release\AFS.dll cui\AFS.cui
copy H:\crass\cui\Musica\Release\Musica.dll cui\Musica.cui
copy H:\crass\cui\sas5\Release\sas5.dll cui\sas5.cui
copy H:\crass\cui\RioShiina\Release\RioShiina.dll cui\RioShiina.cui
copy H:\crass\cui\LiveMaker\Release\LiveMaker.dll cui\LiveMaker.cui
copy H:\crass\cui\KaGuYa\Release\KaGuYa.dll cui\KaGuYa.cui
copy H:\crass\cui\ARCX\Release\ARCX.dll cui\ARCX.cui
copy H:\crass\cui\DCPK\Release\DCPK.dll cui\DCPK.cui
copy H:\crass\cui\EMengine\Release\EMengine.dll cui\EMengine.cui
copy "H:\crass\cui\ADV+++\Release\ADVppp.dll" "cui\ADV+++.cui"
copy H:\crass\cui\ADVEngineMoon\Release\ADVEngineMoon.dll cui\ADVEngineMoon.cui
copy H:\crass\cui\aselia\Release\aselia.dll cui\aselia.cui
copy H:\crass\cui\CaramelBox\Release\CaramelBox.dll cui\CaramelBox.cui
copy H:\crass\cui\Leaf\Release\Leaf.dll cui\Leaf.cui
copy H:\crass\cui\YSO\Release\YSO.dll cui\YSO.cui
copy H:\crass\cui\MAI\Release\MAI.dll cui\MAI.cui
copy H:\crass\cui\AdvSys\Release\AdvSys.dll cui\AdvSys.cui
copy H:\crass\cui\ARCGameEngine\Release\ARCGameEngine.dll cui\ARCGameEngine.cui
copy H:\crass\cui\Selen\Release\Selen.dll cui\Selen.cui
copy H:\crass\cui\AVG32\Release\AVG32.dll cui\AVG32.cui
copy "H:\crass\cui\A98SYS ENGINE\Release\A98SYS ENGINE.dll" "cui\A98SYS ENGINE.cui"
copy "H:\crass\cui\MultiObjects-ScriptEngine\Release\MultiObjects_ScriptEngine.dll" "cui\MultiObjects-ScriptEngine.cui"
copy H:\crass\cui\KAAS\Release\KAAS.dll cui\KAAS.cui
copy H:\crass\cui\rUGP\Release\rUGP.dll cui\rUGP.cui
copy H:\crass\cui\AI5WIN\Release\AI5WIN.dll cui\AI5WIN.cui
copy H:\crass\cui\NECHAOS\Release\NECHAOS.dll cui\NECHAOS.cui
copy H:\crass\cui\MAIKA\Release\MAIKA.dll cui\MAIKA.cui
copy H:\crass\cui\SFA\Release\SFA.dll cui\SFA.cui
copy H:\crass\cui\kid\Release\kid.dll cui\kid.cui
copy H:\crass\cui\TechArts3D\Release\TechArts3D.dll cui\TechArts3D.cui
copy H:\crass\cui\DAC\Release\DAC.dll cui\DAC.cui
copy H:\crass\cui\NPS\Release\NPS.dll cui\NPS.cui
copy H:\crass\cui\CatSystem2\Release\CatSystem2.dll cui\CatSystem2.cui
copy H:\crass\cui\SPack\Release\SPack.dll cui\SPack.cui
copy H:\crass\cui\ohgetsu\Release\ohgetsu.dll cui\ohgetsu.cui
copy H:\crass\cui\ClassicalMoon\Release\ClassicalMoon.dll cui\ClassicalMoon.cui
copy H:\crass\cui\VALKYRIA\Release\VALKYRIA.dll cui\VALKYRIA.cui
copy H:\crass\cui\ARCG\Release\ARCG.dll cui\ARCG.cui
copy H:\crass\cui\Csystem\Release\Csystem.dll cui\Csystem.cui
copy H:\crass\cui\SystemAoi\Release\SystemAoi.dll cui\SystemAoi.cui
copy H:\crass\cui\DMC4\Release\DMC4.dll cui\DMC4.cui
copy H:\crass\cui\ADVSystem\Release\ADVSystem.dll cui\ADVSystem.cui
copy H:\crass\cui\Touhou11\Release\Touhou11.dll cui\Touhou11.cui
copy H:\crass\cui\RealLive\Release\RealLive.dll cui\RealLive.cui
copy H:\crass\cui\KineticNovel\Release\KineticNovel.dll cui\KineticNovel.cui
copy "H:\crass\cui\FFA SYSTEM\Release\FFA SYSTEM.dll" "cui\FFA SYSTEM.cui"
copy H:\crass\cui\gmf\Release\gmf.dll cui\gmf.cui
copy H:\crass\cui\System4\Release\System4.dll cui\System4.cui
copy H:\crass\cui\ANOS\Release\ANOS.dll cui\ANOS.cui
copy H:\crass\cui\Xuse\Release\Xuse.dll cui\Xuse.cui
copy H:\crass\cui\cmvs\Release\cmvs.dll cui\cmvs.cui
copy "H:\crass\cui\Game Script Player\Release\Game Script Player.dll" "cui\Game Script Player.cui"
copy H:\crass\cui\FinalJustice\Release\FinalJustice.dll cui\FinalJustice.cui
copy H:\crass\cui\ScenePlayer\Release\ScenePlayer.dll cui\ScenePlayer.cui
copy H:\crass\cui\GrowLanser\Release\GrowLanser.dll cui\GrowLanser.cui
copy H:\crass\cui\KScriptEngine\Release\KScriptEngine.dll cui\KScriptEngine.cui
copy H:\crass\cui\Seraphim\Release\Seraphim.dll cui\Seraphim.cui
copy H:\crass\cui\mgos\Release\mgos.dll cui\mgos.cui
copy H:\crass\cui\ZWEI2\Release\ZWEI2.dll cui\ZWEI2.cui
copy H:\crass\cui\Adv\Release\Adv.dll cui\Adv.cui
copy H:\crass\cui\EntisGLS\Release\EntisGLS.dll cui\EntisGLS.cui
copy "H:\crass\cui\SCI System\debug\SCI System.dll" "cui\SCI System.cui"
copy H:\crass\cui\Selene\Release\Selene.dll cui\Selene.cui
copy H:\crass\cui\Echeross\Release\Echeross.dll cui\Echeross.cui
copy H:\crass\cui\GXTH\Release\GXTH.dll cui\GXTH.cui
copy H:\crass\cui\CLS\Release\CLS.dll cui\CLS.cui
copy H:\crass\cui\bakuretsu\Release\bakuretsu.dll cui\bakuretsu.cui
copy H:\crass\cui\WindomXP\Release\WindomXP.dll cui\WindomXP.cui
copy H:\crass\cui\FS3D\Release\FS3D.dll cui\FS3D.cui
copy H:\crass\cui\pokoten2\Release\pokoten2.dll cui\pokoten2.cui
copy H:\crass\cui\MacromediaFlash\Release\MacromediaFlash.dll cui\MacromediaFlash.cui
copy H:\crass\cui\SRSPlayer\Release\SRSPlayer.dll cui\SRSPlayer.cui
copy H:\crass\cui\GPLAY\Release\GPLAY.dll cui\GPLAY.cui
copy H:\crass\cui\usi\Release\usi.dll cui\usi.cui
copy H:\crass\cui\gbyFlagGame\Release\gbyFlagGame.dll cui\gbyFlagGame.cui
copy H:\Crass\cui\ValkyrieComplex\Release\ValkyrieComplex.dll cui\ValkyrieComplex.cui
copy H:\Crass\cui\ComicPlayer2\Release\ComicPlayer2.dll cui\ComicPlayer2.cui
copy H:\Crass\cui\ggRMV\Release\ggRMV.dll cui\ggRMV.cui
copy H:\Crass\cui\Ellefin_Game_System\release\Ellefin_Game_System.dll "cui\Ellefin Game System.cui"
copy H:\Crass\cui\WILD_BUG\release\WILD_BUG.dll "cui\WILD_BUG.cui"
copy H:\Crass\cui\AVGEngine\release\AVGEngine.dll "cui\AVGEngine.cui"
copy H:\Crass\cui\RISUSOFT\release\RISUSOFT.dll "cui\RISUSOFT.cui"
copy H:\Crass\cui\WGame\release\WGame.dll "cui\WGame.cui"
copy "H:\Crass\cui\Irrlicht Engine\release\Irrlicht Engine.dll" "cui\Irrlicht Engine.cui"
copy H:\crass\cui\MNP\Release\MNP.dll cui\MNP.cui
copy H:\crass\cui\vnengine\Release\vnengine.dll cui\vnengine.cui
copy H:\crass\cui\kagura\Release\kagura.dll cui\kagura.cui
copy H:\crass\cui\DXArchive\Release\DXArchive.dll cui\DXArchive.cui
copy H:\crass\cui\Primel\Release\Primel.dll cui\Primel.cui
copy H:\crass\cui\BasiL\Release\BasiL.dll cui\BasiL.cui

copy "H:\crass\cui-1.0.4\RPM ADV SYSTEM\Release\RPM_ADV_SYSTEM.dll" "cui\RPM ADV SYSTEM.cui"
copy H:\crass\cui-1.0.4\Lambda\Release\Lambda.dll cui\Lambda.cui
copy "H:\crass\cui-1.0.4\Majiro Script Engine\Majiro_Script_Engine___Win32_Release\Majiro Script Engine.dll" "cui\Majiro Script Engine.cui"
copy H:\crass\cui-1.0.4\AiSystem\Release\AiSystem.dll cui\AiSystem.cui
copy H:\crass\cui-1.0.4\AGSD\Release\AGSD.dll cui\AGSD.cui
copy H:\crass\cui-1.0.4\NAGS\Release\NAGS.dll cui\NAGS.cui

copy H:\crass\cui-1.0.4\AdvTry\Release\AdvTry.dll cui\AdvTry.cui
copy H:\crass\cui-1.0.4\Lua\Release\Lua.dll cui\Lua.cui
copy H:\crass\cui-1.0.4\YELLOWPIG\Release\YELLOWPIG.dll cui\YELLOWPIG.cui
copy H:\crass\cui-1.0.4\Stuff\Release\Stuff.dll cui\Stuff.cui
copy H:\crass\cui-1.0.4\NScripter\Release\NScripter.dll cui\NScripter.cui
copy H:\crass\cui-1.0.4\hcsystem\Release\hcsystem.dll cui\hcsystem.cui
copy H:\crass\cui-1.0.4\NekoSDK\Release\NekoSDK.dll cui\NekoSDK.cui
copy H:\crass\cui-1.0.4\kirikiri2\Release\kirikiri2.dll cui\kirikiri2.cui
copy H:\crass\cui-1.0.4\ego\Release\ego.dll cui\ego.cui
copy H:\crass\cui-1.0.4\Touhou105\Release\Touhou105.dll cui\Touhou105.cui
copy H:\crass\cui-1.0.4\MainProgramHoep\Release\MainProgramHoep.dll cui\MainProgramHoep.cui
copy H:\crass\cui-1.0.4\GScripter\Release\GScripter.dll cui\GScripter.cui
copy H:\crass\cui-1.0.4\ESCARC\Release\ESCARC.dll cui\ESCARC.cui
copy H:\crass\cui-1.0.4\ACTGS\Release\ACTGS.dll cui\ACTGS.cui
copy H:\crass\cui-1.0.4\ags\Release\ags.dll cui\ags.cui
copy H:\crass\cui-1.0.4\SHSystem\Release\SHSystem.dll cui\SHSystem.cui
copy H:\crass\cui-1.0.4\BGI\Release\BGI.dll cui\BGI.cui
copy H:\crass\cui-1.0.4\RAGE\Release\RAGE.dll cui\RAGE.cui
copy H:\crass\cui-1.0.4\FFDSystem\Release\FFDSystem.dll cui\FFDSystem.cui
copy H:\crass\cui-1.0.4\EAGLS\Release\EAGLS.dll cui\EAGLS.cui
copy H:\crass\cui-1.0.4\SystemC\Release\SystemC.dll cui\SystemC.cui
copy H:\crass\cui-1.0.4\AST\Release\AST.dll cui\AST.cui
copy H:\crass\cui-1.0.4\NekoBoard\Release\NekoBoard.dll cui\NekoBoard.cui
copy H:\crass\cui-1.0.4\SOFTPAL_ADV_SYSTEM\Release\SOFTPAL_ADV_SYSTEM.dll "cui\SOFTPAL ADV SYSTEM.cui"
copy H:\crass\cui-1.0.4\Willadv\Release\Willadv.dll cui\Willadv.cui
copy H:\crass\cui-1.0.4\AIL\Release\AIL.dll cui\AIL.cui
copy H:\crass\cui-1.0.4\N2System\Release\N2System.dll cui\N2System.cui
copy H:\crass\cui-1.0.4\IAGS\Release\IAGS.dll cui\IAGS.cui
copy H:\crass\cui-1.0.4\MOONHIR\Release\MOONHIR.dll cui\MOONHIR.cui
copy H:\crass\cui-1.0.4\LC-ScriptEngine\Release\LC_ScriptEngine.dll cui\LC-ScriptEngine.cui
copy H:\crass\cui-1.0.4\HSP\Release\HSP.dll cui\HSP.cui
copy H:\crass\cui-1.0.4\\GMMSystem\Release\GMMSystem.dll cui\GMMSystem.cui
copy H:\crass\cui-1.0.4\GameScripter\Release\GameScripter.dll cui\GameScripter.cui
copy H:\crass\cui-1.0.4\EtherVapor\Release\EtherVapor.dll cui\EtherVapor.cui
copy H:\crass\cui-1.0.4\k_archiver\Release\k_archiver.dll cui\k_archiver.cui
copy H:\crass\cui-1.0.4\GPK2\Release\GPK2.dll cui\GPK2.cui
copy H:\crass\cui-1.0.4\MBA\Release\MBA.dll cui\MBA.cui
copy H:\crass\cui-1.0.4\NRTS\Release\NRTS.dll cui\NRTS.cui
copy H:\crass\cui-1.0.4\losterika\Release\losterika.dll cui\losterika.cui
copy H:\crass\cui-1.0.4\dibsec32\Release\dibsec32.dll cui\dibsec32.cui
copy H:\crass\cui-1.0.4\YukaScript\Release\YukaScript.dll cui\YukaScript.cui
copy H:\crass\cui-1.0.4\GameSys\Release\GameSys.dll cui\GameSys.cui
copy H:\crass\cui-1.0.4\TEATIME\Release\TEATIME.dll cui\TEATIME.cui
copy H:\crass\cui-1.0.4\FORIS\Release\FORIS.dll cui\FORIS.cui
copy H:\crass\cui-1.0.4\ym1n2\Release\ym1n2.dll cui\ym1n2.cui
copy H:\crass\cui-1.0.4\SystemNNN\Release\SystemNNN.dll cui\SystemNNN.cui
copy H:\crass\cui-1.0.4\SLGSystem\Release\SLGSystem.dll cui\SLGSystem.cui
copy H:\crass\cui-1.0.4\DenSDK\Release\DenSDK.dll cui\DenSDK.cui
copy H:\crass\cui-1.0.4\taskforce\Release\taskforce.dll cui\taskforce.cui
copy H:\crass\cui-1.0.4\mts\Release\mts.dll cui\mts.cui
copy H:\crass\cui-1.0.4\SaiSys\Release\SaiSys.dll cui\SaiSys.cui
copy H:\crass\cui-1.0.4\AI6WIN\Release\AI6WIN.dll cui\AI6WIN.cui
copy H:\crass\cui-1.0.4\TACTICS_ARC\Release\TACTICS_ARC.dll cui\TACTICS_ARC.cui
copy H:\crass\cui-1.0.4\PJADV\Release\PJADV.dll cui\PJADV.cui
copy H:\crass\cui-1.0.4\CScript\Release\CScript.dll cui\CScript.cui
copy H:\crass\cui-1.0.4\ADVDX\Release\ADVDX.dll cui\ADVDX.cui
copy H:\crass\cui-1.0.4\Luna\Release\Luna.dll cui\Luna.cui
copy H:\crass\cui-1.0.4\pk\Release\pk.dll cui\pk.cui
copy H:\crass\cui-1.0.4\ZG_Engine\Release\ZG_Engine.dll cui\ZG-Engine.cui
copy H:\crass\cui-1.0.4\GsWin\Release\GsWin.dll cui\GsWin.cui
copy H:\crass\cui-1.0.4\AGS32i\Release\AGS32i.dll cui\AGS32i.cui
copy H:\crass\cui-1.0.4\BELLDA\Release\BELLDA.dll cui\BELLDA.cui
copy H:\crass\cui-1.0.4\DISTORTION\Release\DISTORTION.dll cui\DISTORTION.cui
copy H:\crass\cui-1.0.4\FVP\Release\FVP.dll cui\FVP.cui
copy H:\crass\cui-1.0.4\MalieSystem\Release\MalieSystem.dll cui\MalieSystem.cui
copy H:\crass\cui-1.0.4\NEJII\Release\NEJII.dll cui\NEJII.cui
copy H:\crass\cui-1.0.4\route2\Release\route2.dll cui\route2.cui
copy H:\crass\cui-1.0.4\IPAC\Release\IPAC.dll cui\IPAC.cui
copy H:\crass\cui-1.0.4\DJSYSTEM\Release\DJSYSTEM.dll cui\DJSYSTEM.cui
copy H:\crass\cui-1.0.4\DDSystem\Release\DDSystem.dll cui\DDSystem.cui
copy H:\crass\cui-1.0.4\ISM\Release\ISM.dll cui\ISM.cui
copy H:\crass\cui-1.0.4\NitroPlus\Release\NitroPlus.dll cui\NitroPlus.cui
copy H:\crass\cui-1.0.4\666-SYSTEM\Release\666_SYSTEM.dll cui\666-SYSTEM.cui
copy H:\crass\cui-1.0.4\NeXAS\Release\NeXAS.dll cui\NeXAS.cui
copy H:\crass\cui-1.0.4\SoW\Release\SoW.dll cui\SoW.cui
copy H:\crass\cui-1.0.4\TonyAlbum\Release\TonyAlbum.dll cui\TonyAlbum.cui

copy H:\crass\io_request\Release\io_request.dll .\
copy H:\crass\utility\Release\utility.dll .\
copy H:\crass\acui_core\Release\acui_core.dll .\
copy H:\crass\package_core\Release\package_core.dll .\
copy H:\crass\resource_core\Release\resource_core.dll .\
copy H:\crass\locale\Release\locale.dll .\
copy H:\crass\language\English\Release\English.dll language\English.loc
copy H:\crass\language\SimplifiedChinese\Release\SimplifiedChinese.dll language\SimplifiedChinese.loc
copy H:\crass\language\TraditionalChinese\Release\TraditionalChinese.dll language\TraditionalChinese.loc
copy H:\crass\language\Japanese\Release\Japanese.dll language\Japanese.loc



